name: "Update HM Options"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:


jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install cheerio
      - run: bun run lib/scrape.ts
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update options $(date -u)"
          git push
